// Code generated by "stringer -type=ItemType"; DO NOT EDIT.

package lexer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ItemEOF-0]
	_ = x[ItemEOL-1]
	_ = x[ItemError-2]
	_ = x[ItemDecimal-3]
	_ = x[ItemHexadecimal-4]
	_ = x[ItemOctal-5]
	_ = x[ItemOperator-6]
}

const _ItemType_name = "ItemEOFItemEOLItemErrorItemDecimalItemHexadecimalItemOctalItemOperator"

var _ItemType_index = [...]uint8{0, 7, 14, 23, 34, 49, 58, 70}

func (i ItemType) String() string {
	if i < 0 || i >= ItemType(len(_ItemType_index)-1) {
		return "ItemType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ItemType_name[_ItemType_index[i]:_ItemType_index[i+1]]
}
